### ISSUE TITLE
Problemas do readme.md

### ISSUE THREAD

**Issue by mbacefor** [Andrejmrocha/Crushed-Craft#1]
1. Objetivo: Nesse tópico deve conter o objetivo do seu jogo;
2. Valor agregado:  O designer do jogo ainda esta muito semelhante ao tradicional
3. Fases: Detalhar melhor como serão as fases. Pode ter só uma, mas precisa de detalhes
4. Esquema de pontuação: OK
5. Requisitos: Esta faltando a tela de inicio, pontuação e ajuda pelo menos. Seria legal ter um placar.
6. Protótipo das telas: Falta
7. Tecnologias e Ferramentas utilizadas: Falta colocar algumas ferramentas como: Visualcode, git, etc

[Link artefato](https://github.com/Andrejmrocha/Crush-Craft/blob/main/readme.md)

**Comment by Andrejmrocha** [comment]
Correções concluídas
